import type { Metadata } from "next"
import { Roboto } from 'next/font/google'
import Navbar from "@/components/navbar/Navbar"
import Footer from "@/components/footer/Footer"
import cls from "classnames"
import "./globals.css"

const robot = Roboto({
    weight: ["300", "400", "700"],
    subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cls(robot.className, "bg-bg")}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
